name: Modify ICS Calendar

on:
  schedule:
    - cron: "0 0 1 * *"  # 每月1日 00:00 UTC 运行
  workflow_dispatch:

jobs:
  modify_ics:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install icalendar requests

      - name: Download and modify ICS
        run: |
          python3 modify_ics.py

      - name: List files in the directory
        run: |
          ls -l

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update ics
